# Generated by Django 5.2.15 on 2026-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='date',
            field=models.DateField(),
        ),
    ]
